Create table LMS_MEMBERS
(
	MEMBER_ID VARCHAR(10),
	MEMBER_NAME VARCHAR(30) NOT NULL,
	CITY VARCHAR(20),
	DATE_REGISTER DATETIME NOT NULL,
	DATE_EXPIRE DATETIME ,
	MEMBERSHIP_STATUS VARCHAR(15) NOT NULL,
	CONSTRAINT LMS_cts1 PRIMARY KEY(MEMBER_ID)
);

Create table LMS_SUPPLIERS_DETAILS
(
	SUPPLIER_ID VARCHAR(3),
	SUPPLIER_NAME VARCHAR(30) NOT NULL,
	ADDRESS	VARCHAR(50),
	CONTACT INT NOT NULL,
	EMAIL VARCHAR(15) NOT NULL,
	CONSTRAINT LMS_cts2 PRIMARY KEY(SUPPLIER_ID)
);

Create table LMS_FINE_DETAILS
(
	FINE_RANGE VARCHAR(3),
	FINE_AMOUNT DECIMAL(10,2) NOT NULL,
	CONSTRAINT LMS_cts3 PRIMARY KEY(FINE_RANGE)
);


Create table LMS_BOOK_DETAILS
(
	BOOK_CODE VARCHAR(10),	
	BOOK_TITLE VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(15) NOT NULL,
	AUTHOR VARCHAR(30) NOT NULL,
	PUBLICATION VARCHAR(30),
	PUBLISH_DATE DATETIME,
	BOOK_EDITION INT,
	PRICE DECIMAL(8,2) NOT NULL,	
	RACK_NUM VARCHAR(3),
	DATE_ARRIVAL DATETIME NOT NULL, 		
	SUPPLIER_ID VARCHAR(3) NOT NULL,
	CONSTRAINT LMS_cts4 PRIMARY KEY(BOOK_CODE), 
    CONSTRAINT LMS_cts41 FOREIGN KEY(SUPPLIER_ID) REFERENCES LMS_SUPPLIERS_DETAILS(SUPPLIER_ID)
);


Create table LMS_BOOK_ISSUE
(
	BOOK_ISSUE_NO INT,
	MEMBER_ID VARCHAR(10) NOT NULL,
	BOOK_CODE VARCHAR(10) NOT NULL,
	DATE_ISSUE DATETIME NOT NULL,
	DATE_RETURN DATETIME NOT NULL,
    DATE_RETURNED DATETIME NULL,
	BOOK_ISSUE_STATUS VARCHAR(20) NOT NULL,
	FINE_RANGE VARCHAR(3),
	CONSTRAINT LMS_cts5 PRIMARY KEY(BOOK_ISSUE_NO),
    CONSTRAINT LMS_Mem FOREIGN KEY(MEMBER_ID) REFERENCES LMS_MEMBERS(MEMBER_ID),
    CONSTRAINT LMS_BookDetail FOREIGN KEY(BOOK_CODE) REFERENCES LMS_BOOK_DETAILS(BOOK_CODE),
	CONSTRAINT LMS_FineDetail FOREIGN KEY(FINE_RANGE) REFERENCES LMS_FINE_DETAILS(FINE_RANGE)
);