-- Simple Questions

-- Problem #1
SELECT MEMBER_ID, MEMBER_NAME, CITY, MEMBERSHIP_STATUS
FROM LMS_MEMBERS
WHERE MEMBERSHIP_STATUS = 'Permanent';

-- Problem #2
SELECT MEMBER_ID, MEMBER_NAME
FROM LMS_MEMBERS
WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM LMS_BOOK_ISSUE WHERE BOOK_ISSUE_STATUS = 'N');

-- Problem #3
SELECT M.MEMBER_ID, M.MEMBER_NAME
FROM LMS_MEMBERS M
JOIN LMS_BOOK_ISSUE I ON M.MEMBER_ID = I.MEMBER_ID
WHERE I.BOOK_CODE = 'BL000002';

-- Problem #4
SELECT BOOK_CODE, BOOK_TITLE, AUTHOR
FROM LMS_BOOK_DETAILS
WHERE AUTHOR LIKE 'P%';

-- Problem #5
SELECT COUNT(*) AS NO_OF_BOOKS
FROM LMS_BOOK_DETAILS
WHERE CATEGORY = 'JAVA';

-- Problem #6
SELECT CATEGORY, COUNT(*) AS NO_OF_BOOKS
FROM LMS_BOOK_DETAILS
GROUP BY CATEGORY;

-- Problem #7
SELECT COUNT(*) AS NO_OF_BOOKS
FROM LMS_BOOK_DETAILS
WHERE PUBLICATION = 'Prentice Hall';

-- Problem #8
SELECT B.BOOK_CODE, B.BOOK_TITLE
FROM LMS_BOOK_DETAILS B
JOIN LMS_BOOK_ISSUE I ON B.BOOK_CODE = I.BOOK_CODE
WHERE I.DATE_ISSUE = '2012-04-01';

-- Problem #9
SELECT MEMBER_ID, MEMBER_NAME, DATE_REGISTER, DATE_EXPIRE
FROM LMS_MEMBERS
WHERE DATE_EXPIRE < '2013-04-01';

-- Problem #10
SELECT MEMBER_ID, MEMBER_NAME, DATE_REGISTER, MEMBERSHIP_STATUS
FROM LMS_MEMBERS
WHERE DATE_REGISTER < '2012-03-01' AND MEMBERSHIP_STATUS = 'Temporary';

-- Problem #11
SELECT MEMBER_ID, UPPER(MEMBER_NAME) AS Name
FROM LMS_MEMBERS
WHERE CITY IN ('CHENNAI', 'DELHI');

-- Problem #12
SELECT DISTINCT BOOK_TITLE + '_is_written_by_' + AUTHOR AS BOOK_WRITTEN_BY
FROM LMS_BOOK_DETAILS;

-- Problem #13
SELECT AVG(PRICE) AS AVERAGEPRICE
FROM LMS_BOOK_DETAILS
WHERE CATEGORY = 'JAVA';

-- Problem #14
SELECT SUPPLIER_ID, SUPPLIER_NAME, EMAIL
FROM LMS_SUPPLIERS_DETAILS
WHERE EMAIL LIKE '%gmail.com';

-- Problem #15
SELECT SUPPLIER_ID, SUPPLIER_NAME, COALESCE(CAST(CONTACT AS VARCHAR), EMAIL, ADDRESS) AS CONTACTDETAILS
FROM LMS_SUPPLIERS_DETAILS;

-- Problem #16
SELECT SUPPLIER_ID, SUPPLIER_NAME, IIF(CONTACT IS NOT NULL, 'Yes', 'No') AS PHONENUMAVAILABLE
FROM LMS_SUPPLIERS_DETAILS;

-- Average Questions

-- Problem #1
SELECT M.MEMBER_ID, M.MEMBER_NAME, B.BOOK_CODE, B.BOOK_TITLE
FROM LMS_MEMBERS M
JOIN LMS_BOOK_ISSUE I ON M.MEMBER_ID = I.MEMBER_ID
JOIN LMS_BOOK_DETAILS B ON I.BOOK_CODE = B.BOOK_CODE;

-- Problem #2
SELECT COUNT(*) AS NO_OF_BOOKS_AVAILABLE
FROM LMS_BOOK_DETAILS
WHERE BOOK_CODE NOT IN (SELECT BOOK_CODE FROM LMS_BOOK_ISSUE WHERE BOOK_ISSUE_STATUS = 'N');

-- Problem #3
SELECT M.MEMBER_ID, M.MEMBER_NAME, F.FINE_RANGE, F.FINE_AMOUNT
FROM LMS_MEMBERS M
JOIN LMS_BOOK_ISSUE I ON M.MEMBER_ID = I.MEMBER_ID
JOIN LMS_FINE_DETAILS F ON I.FINE_RANGE = F.FINE_RANGE
WHERE F.FINE_AMOUNT < 100;

-- Problem #4
SELECT B.BOOK_CODE, B.BOOK_TITLE, IIF(I.BOOK_ISSUE_STATUS = 'N', 'Not Available', 'Available') AS AVAILABILITYSTATUS
FROM LMS_BOOK_DETAILS B
LEFT JOIN LMS_BOOK_ISSUE I ON B.BOOK_CODE = I.BOOK_CODE
WHERE B.CATEGORY = 'JAVA' AND B.BOOK_EDITION = 6;

-- Problem #5
SELECT BOOK_CODE, BOOK_TITLE, RACK_NUM
FROM LMS_BOOK_DETAILS
WHERE RACK_NUM = 'A1'
ORDER BY BOOK_TITLE;

-- Problem #6
SELECT M.MEMBER_ID, M.MEMBER_NAME, I.DATE_RETURN AS DUE_DATE, I.DATE_RETURNED
FROM LMS_MEMBERS M
JOIN LMS_BOOK_ISSUE I ON M.MEMBER_ID = I.MEMBER_ID
WHERE I.DATE_RETURNED > I.DATE_RETURN;

-- Problem #7
SELECT MEMBER_ID, MEMBER_NAME, DATE_REGISTER
FROM LMS_MEMBERS
WHERE MEMBER_ID NOT IN (SELECT MEMBER_ID FROM LMS_BOOK_ISSUE);

-- Problem #8
SELECT M.MEMBER_ID, M.MEMBER_NAME
FROM LMS_MEMBERS M
WHERE NOT EXISTS (SELECT 1 FROM LMS_BOOK_ISSUE I WHERE I.MEMBER_ID = M.MEMBER_ID AND YEAR(I.DATE_ISSUE) = 2012 AND I.FINE_RANGE IS NOT NULL);

-- Problem #9
WITH IssueCounts AS (
    SELECT DATE_ISSUE, COUNT(*) AS NOOFBOOKS
    FROM LMS_BOOK_ISSUE
    GROUP BY DATE_ISSUE
)
SELECT DATE_ISSUE, NOOFBOOKS
FROM IssueCounts
WHERE NOOFBOOKS = (SELECT MAX(NOOFBOOKS) FROM IssueCounts);

-- Problem #10
SELECT BOOK_TITLE, SUPPLIER_ID
FROM LMS_BOOK_DETAILS
WHERE AUTHOR = 'Herbert Schildt' AND BOOK_EDITION = 5 AND SUPPLIER_ID = 'S01';

-- Problem #11
SELECT RACK_NUM, COUNT(*) AS NOOFBOOKS
FROM LMS_BOOK_DETAILS
GROUP BY RACK_NUM
ORDER BY RACK_NUM;

-- Problem #12
SELECT I.BOOK_ISSUE_NO, M.MEMBER_NAME, M.DATE_REGISTER, M.DATE_EXPIRE, B.BOOK_TITLE, B.CATEGORY, B.AUTHOR, B.PRICE, I.DATE_ISSUE, I.DATE_RETURN, I.DATE_RETURNED, I.BOOK_ISSUE_STATUS, F.FINE_AMOUNT
FROM LMS_BOOK_ISSUE I
JOIN LMS_MEMBERS M ON I.MEMBER_ID = M.MEMBER_ID
JOIN LMS_BOOK_DETAILS B ON I.BOOK_CODE = B.BOOK_CODE
LEFT JOIN LMS_FINE_DETAILS F ON I.FINE_RANGE = F.FINE_RANGE;

-- Problem #13
SELECT BOOK_CODE, BOOK_TITLE, PUBLISH_DATE
FROM LMS_BOOK_DETAILS
WHERE MONTH(PUBLISH_DATE) = 12;

-- Problem #14
SELECT B.BOOK_CODE, B.BOOK_TITLE, IIF(I.BOOK_ISSUE_STATUS = 'N', 'Not Available', 'Available') AS AVAILABILITYSTATUS
FROM LMS_BOOK_DETAILS B
LEFT JOIN LMS_BOOK_ISSUE I ON B.BOOK_CODE = I.BOOK_CODE
WHERE B.CATEGORY = 'JAVA' AND B.BOOK_EDITION = 5;

-- Complex Questions

-- Problem #1
SELECT B.BOOK_CODE, B.BOOK_TITLE, S.SUPPLIER_NAME
FROM LMS_BOOK_DETAILS B
JOIN LMS_SUPPLIERS_DETAILS S ON B.SUPPLIER_ID = S.SUPPLIER_ID
WHERE S.SUPPLIER_ID = (SELECT TOP 1 SUPPLIER_ID FROM LMS_BOOK_DETAILS GROUP BY SUPPLIER_ID ORDER BY COUNT(*) DESC);

-- Problem #2
SELECT M.MEMBER_ID, M.MEMBER_NAME, 3 - COUNT(I.BOOK_ISSUE_NO) AS REMAININGBOOKS
FROM LMS_MEMBERS M
LEFT JOIN LMS_BOOK_ISSUE I ON M.MEMBER_ID = I.MEMBER_ID AND I.BOOK_ISSUE_STATUS = 'N'
GROUP BY M.MEMBER_ID, M.MEMBER_NAME;

-- Problem #3
SELECT SUPPLIER_ID, SUPPLIER_NAME
FROM LMS_SUPPLIERS_DETAILS
WHERE SUPPLIER_ID = (SELECT TOP 1 SUPPLIER_ID FROM LMS_BOOK_DETAILS GROUP BY SUPPLIER_ID ORDER BY COUNT(*) ASC);